### ISSUE TITLE
Figure 6 in paper

### ISSUE THREAD

**Issue by dsvilarkovic** [gregorbachmann/scaling_mlps#1]
Hello, 
Nice paper, I was wondering could you explain what do labels in figure 6 mean? I assume it's not the parameter count given that it is show on the x-axis?
![image](https://github.com/gregorbachmann/scaling_mlps/assets/18049803/9590a346-3472-43d0-a4e8-279daf5c595b)

**Comment by gregorbachmann** [comment]
Hi!
Thanks for checking out our work! Sorry that's indeed a bit unclear, the x-axis denotes the size of the model and the labels denote the number of samples used for training. So for instance the curve closest to the bottom depicts differently sized models, all trained with 11801680 samples. The curve one above is all models trained with 4194304 samples etc. It would maybe have been better to color the entire curve according to the sample size color.
I hope this clarifies things!

**Comment by dsvilarkovic** [comment]
It's clear now! I skimmed through the paper and it wasn't quite clear from the text description what the numbers meant. If I was more into the neural scaling laws, I would've probably realized it earlier. Color choice is fine, no need to change imo!
