### ISSUE TITLE
Having an error while following the demo to load a pretrained model

### ISSUE THREAD

**Issue by minkiml** [gregorbachmann/scaling_mlps#2]
Thank you for your great work! I really appreciate your study and contributions to exploring and understanding MLPs deeper. 

I would like to explore some of the pretrained MLPs and am trying to load one of them by following your demo note explore.ipynb. 
But unfortunately, I encountered an error from running the line

model = get_model(architecture=architecture, resolution=crop_resolution, num_classes=CLASS_DICT[dataset],
                  checkpoint='in21k_cifar10')
                  
The error I got is as follows 
  File "/.../networks.py", line 106, in load
    for k, v in torch.load(weight_path).items()
  File "/.../.conda/envs/DL_venv/lib/python3.9/site-packages/torch/serialization.py", line 608, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/.../.conda/envs/DL_venv/lib/python3.9/site-packages/torch/serialization.py", line 777, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: invalid load key, '<'.

Can I please get some advice on how to fix this?

Thanks in advance.

**Comment by gregorbachmann** [comment]
Hi!

Thanks so much for checking out our work! 

I just took a look and I think the provided links to Google Drive somehow expired. I updated the responsible file and at least on my side the weights are again automatically downloaded. Let me know if you still cannot load the weights!

**Comment by minkiml** [comment]
Thank you for your help. 
It now gets loaded!
