### ISSUE TITLE
How is the finetuning done?

### ISSUE THREAD

**Issue by minkiml** [gregorbachmann/scaling_mlps#3]
Hi, 
I am curious how the finetuning is done to produce the results in the main work.

Is it linear probing or full finetuning? 

Thanks in advance!

**Comment by gregorbachmann** [comment]
Hi,

The checkpoints we provide here are all full finetuning runs, usually for 20 epochs starting from the pre-trained checkpoints based on ImageNet21k. I think in the paper we describe the finetuning setup (https://arxiv.org/abs/2306.13575) in more detail, and we also provide numbers for the linear transfer case, but I don't think we published the checkpoints as they were always a bit worse than the full finetuning ones. 
Let me know if that helps!

**Comment by minkiml** [comment]
I see. 
I found the section you describe the setup. 
Thank you!
